version: '3.8'

services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  static:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: python -m http.server 3000
